// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Ob__-YCE8OZCLZlBsgV91L4aiZCAJJ8',
    appId: '1:751259560292:web:09e487908a097b1c2cf271',
    messagingSenderId: '751259560292',
    projectId: 'tastesmoketest',
    authDomain: 'tastesmoketest.firebaseapp.com',
    storageBucket: 'tastesmoketest.firebasestorage.app',
    measurementId: 'G-Y5FBR03T7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkNvVP4ZuS2cB7hOcgouKCxnhnEcwcIIQ',
    appId: '1:751259560292:android:9455d7ba90a123522cf271',
    messagingSenderId: '751259560292',
    projectId: 'tastesmoketest',
    storageBucket: 'tastesmoketest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGz0AX8BK86-Px-udmqjRdoP0BfLeV46o',
    appId: '1:751259560292:ios:2b4b0874fe963cd32cf271',
    messagingSenderId: '751259560292',
    projectId: 'tastesmoketest',
    storageBucket: 'tastesmoketest.firebasestorage.app',
    androidClientId: '751259560292-5vqvfl8d7lnb446rj06n68t2cndhkh39.apps.googleusercontent.com',
    iosClientId: '751259560292-1koui73pq5qftkv2081npl5sud9gags1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastesmokeios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGz0AX8BK86-Px-udmqjRdoP0BfLeV46o',
    appId: '1:751259560292:ios:2b4b0874fe963cd32cf271',
    messagingSenderId: '751259560292',
    projectId: 'tastesmoketest',
    storageBucket: 'tastesmoketest.firebasestorage.app',
    androidClientId: '751259560292-5vqvfl8d7lnb446rj06n68t2cndhkh39.apps.googleusercontent.com',
    iosClientId: '751259560292-1koui73pq5qftkv2081npl5sud9gags1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastesmokeios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Ob__-YCE8OZCLZlBsgV91L4aiZCAJJ8',
    appId: '1:751259560292:web:32149afc9f093d222cf271',
    messagingSenderId: '751259560292',
    projectId: 'tastesmoketest',
    authDomain: 'tastesmoketest.firebaseapp.com',
    storageBucket: 'tastesmoketest.firebasestorage.app',
    measurementId: 'G-YHFSXNH6MB',
  );
}
