# PowerShell script for full project clean and rebuild
# Used after removing dependencies like google_sign_in

Write-Host "Full clean of taste_smoke_ios project..." -ForegroundColor Cyan

# Clean Flutter
Write-Host "Cleaning Flutter cache..." -ForegroundColor Yellow
flutter clean
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: flutter clean failed" -ForegroundColor Red
    exit 1
}

flutter pub cache clean
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: flutter pub cache clean failed" -ForegroundColor Red
    exit 1
}

# Remove autogenerated files
Write-Host "Removing autogenerated files..." -ForegroundColor Yellow
if (Test-Path ".dart_tool") { Remove-Item -Recurse -Force ".dart_tool" }
if (Test-Path "build") { Remove-Item -Recurse -Force "build" }
if (Test-Path "pubspec.lock") { Remove-Item -Force "pubspec.lock" }

# Clean iOS dependencies
Write-Host "Cleaning iOS dependencies..." -ForegroundColor Yellow
Push-Location "ios"
if (Test-Path "Pods") { Remove-Item -Recurse -Force "Pods" }
if (Test-Path "Podfile.lock") { Remove-Item -Force "Podfile.lock" }

# Clear DerivedData (if accessible)
$derivedDataPath = "$env:HOME\Library\Developer\Xcode\DerivedData"
if (Test-Path $derivedDataPath) {
    Write-Host "Clearing Xcode DerivedData..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force "$derivedDataPath\*" -ErrorAction SilentlyContinue
}
Pop-Location

# Reinstall dependencies
Write-Host "Installing dependencies..." -ForegroundColor Yellow
flutter pub get
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: flutter pub get failed" -ForegroundColor Red
    exit 1
}

# Clean CocoaPods cache and install
Write-Host "Cleaning CocoaPods cache..." -ForegroundColor Yellow
Push-Location "ios"

# Note: pod cache clean and pod repo update commands require CocoaPods to be installed
# On Windows, this might not be available, so we'll skip them with warnings
try {
    pod cache clean --all 2>$null
    pod repo update 2>$null
    pod install --verbose --repo-update 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "OK: CocoaPods dependencies installed successfully" -ForegroundColor Green
    } else {
        Write-Host "WARNING: CocoaPods commands failed (normal on Windows)" -ForegroundColor Yellow
        Write-Host "RECOMMENDATION: Run these commands on macOS for iOS build" -ForegroundColor Blue
    }
} catch {
    Write-Host "WARNING: CocoaPods not available (normal on Windows)" -ForegroundColor Yellow
    Write-Host "RECOMMENDATION: Run pod install on macOS for iOS build" -ForegroundColor Blue
}

Pop-Location

Write-Host ""
Write-Host "Full clean completed! Project is ready to build." -ForegroundColor Green
Write-Host "For iOS build on macOS: flutter build ios --no-codesign" -ForegroundColor Cyan
Write-Host "For Android build: flutter build apk --debug" -ForegroundColor Cyan