name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0' # Укажите вашу версию Flutter
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
    
    # Сборка без кодовой подписи для AltStore
    - name: Build iOS (no codesign)
      run: flutter build ios --release --no-codesign
    
    - name: Create unsigned IPA
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        cp -r Runner.app Payload/
        zip -r app.ipa Payload/
    
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: release-ipa
        path: build/ios/iphoneos/app.ipa
